### ISSUE TITLE
OSGeo2W Shell Result

### ISSUE THREAD

**Issue by webmap2015** [pramsey/gdal2tilesp#2]
```
               -={ OSGeo4W Shell Commands }=-

   bmp2tiff           geotifcp           ras2tiff
   cs2cs              gif2tiff           raw2tiff
   curl               gltpd              rgb2ycbcr
   dllupdate          listgeo            rpcgen
   example1           nad2bin            testepsg
   example2           nccopy             textreplace
   fax2ps             ncdump             thumbnail
   fax2tiff           ncgen              tiff2bw
   gdaladdo           ncgen3             tiff2pdf
   gdalbuildvrt       nearblack          tiff2ps
   gdaldem            nircmd             tiff2rgba
   gdalenhance        nircmdc            tiffcmp
   gdalinfo           ogdi_import        tiffcp
   gdallocationinfo   ogdi_info          tiffcrop
   gdalmanage         ogr2ogr            tiffdither
   gdalserver         ogrinfo            tiffdump
   gdalsrsinfo        ogrlineref         tiffinfo
   gdaltindex         ogrtindex          tiffmedian
   gdaltransform      osgeo4w-setup      tiffset
   gdalwarp           pal2rgb            tiffsplit
   gdal_contour       ppm2tiff           xmlcatalog
   gdal_grid          proj               xmllint
   gdal_rasterize     psql               xmlwf
   gdal_translate     python             xxmklink
   geod               pythonw


   epsg_tr           gdalimport        make-bat-for-py
   esri2wkt          gdalmove          mkgraticule
   gcps2vec          gdal_auth         o-help
   gcps2wld          gdal_calc         o4w_env
   gdal2cesium       gdal_edit         pct2rgb
   gdal2tiles        gdal_fillnodata   rgb2pct
   gdal2tilesp       gdal_merge        setup-test
   gdal2xyz          gdal_polygonize   setup
   gdalchksum        gdal_proximity
   gdalcompare       gdal_retile
   gdalident         gdal_sieve
```

GDAL 1.11.2, released 2015/02/10

C:>gdal2tilesp C:\Users\laptop\Desktop\Tif\my.tif Tile
Process Process-1:
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\multiprocessing\process.py", line 258, in
_bootstrap
    self.run()
  File "C:\OSGEO4~1\apps\Python27\lib\multiprocessing\process.py", line 114, in
run
    self._target(_self._args, *_self._kwargs)
  File "C:\OSGEO4~1\bin\gdal2tilesp.py", line 2293, in worker_metadata
    gdal2tiles.open_input()
  File "C:\OSGEO4~1\bin\gdal2tilesp.py", line 904, in open_input
    os.unlink(tempfilename)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\users\laptop\appdata\local\temp\tmp8kyv9a-gda
l2tiles.vrt'
Generating Base Tiles:
Generating Overview Tiles:
Traceback (most recent call last):
  File "C:\OSGEO4~1\bin\gdal2tilesp.py", line 2346, in <module>
    tminz = zoom_limits.get(timeout=1)
  File "C:\OSGEO4~1\apps\Python27\lib\multiprocessing\queues.py", line 132, in g
et
    raise Empty
Queue.Empty

C:>

**Comment by jhires** [comment]
Is there a workaround for the above issue? I am seeing the same WindowsError: [Error 32]

**Comment by webmap2015** [comment]
Thanks.
